### ISSUE TITLE
Improve Sources

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/gdocs-plugin#1]
Allow sources to be selected from the federated recommender. Beyond that, implement Europeana, Mendeley and ZBW as additional single source by integrating their rest apis. 

Please Document how additional sources can be added to the extension.

**Comment by chseifert** [comment]
With the source selection and the improved recommender this won't be fixed in the deployed version. 
We could offer some "branded" versions for Europeana, but I would schedule that for after the deployment.

**Comment by chseifert** [comment]
Need not focus on this issue anymore. Currently there are no concrete plans for uptake, we will see in the evaluation if some partner will find it useful. In this case we will reopen another issue for the specific partner API.
