### ISSUE TITLE
Advanced search tools

### ISSUE THREAD

**Issue by kunzstef** [EEXCESS/gdocs-plugin#14]
Review:

Consider providing some advance search tools (author, publication type, date, etc etc).  These are usually very important for finding academic/research type publications - often necessary to accurately find a particular article, author, or source. => power search/extended search

**Comment by chseifert** [comment]
As this is not fully supported by the backend, we won't implement it on the client side.

**Comment by chseifert** [comment]
Not on the roadmap anymore (also not on the back-end we are using).
