### ISSUE TITLE
Deploy Plugin in Google App Store

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/gdocs-plugin#2]
...TODO's have been given by google.

**Comment by chseifert** [comment]
Received feedback - request for minor modifications
 https://docs.google.com/document/d/1Tr29OtSDU-sj31Yuqpev-Q88gEfEO9zdamor5ihNaBM/

**Comment by chseifert** [comment]
Don't forget to finish/adapt  comments in review form (see https://github.com/EEXCESS/gdocs-plugin/issues/26) and adapt description etc. during deployment (see https://github.com/EEXCESS/gdocs-plugin/issues/28)

**Comment by kunzstef** [comment]
Add-on submitted to review after TODO's have been fixed.

**Comment by chseifert** [comment]
- [x] Redeploy the current version. All comments should have been fixed now.
