### ISSUE TITLE
improve query

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/gdocs-plugin#20]
Improve search query in the case the text is selected in the document using the following simple rules

(abbreviatons U- upper case word, L - lower case word)
- all upper case words in a sequence are sent as one context keyword, e.g. Ada Lovelace or New York State University, pattern U*
- upper case words separated by max one lower case word are sent as one context keyword, e.g. King of London, pattern U_LU_
  - all other combinations are sent as multiple, separate context keywords

**Comment by philgooch** [comment]
Is it possible to extract the noun phrases or entities from the selected text, and just use these terms in the query?

**Comment by chseifert** [comment]
won't be fixed unless we know better what works from the Chrome extension . Does not make sense to have two lines of investigations how this works.
