### ISSUE TITLE
Logging of user feedback

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/gdocs-plugin#21]
User feedback should be collected, using the following end points
https://github.com/EEXCESS/eexcess/wiki/logging-on-privacy-proxy

(so far only /log/rview, but should in the future include log/used)
see https://github.com/EEXCESS/privacy-proxy/issues/1

**Comment by schloett** [comment]
not 100% sure, but as far as I remember, the logging is deactivated on the privacy proxy atm, will be re-structured and hence I guess the endpoints may change. Probably Thomas/Johannes know more about this.

**Comment by ThomasCerq** [comment]
Jörg is right. It's deactivated for the moment. I guess we would just need to agree on the set of events we want to log. Johannes (and I, and you?) should decide it, and then I will be able to implement it.

**Comment by kunzstef** [comment]
- [x] generate a unique id for the user to identify him when logging: e.g. hash(userid + google docs) -> hash of user's mail address
- [x] add origin: google docs or something like this when logging was implemented on recommender to the request

**Comment by chseifert** [comment]
The logging functionality is described here: 
https://github.com/EEXCESS/eexcess/wiki/EEXCESS---Logging

1) Basically, the "origin" attribute has to be sent with every query request. 
I'd suggest: 
"origin": {
       "clientType": "EEXCESS - Google Docs AddOn",
       "clientVersion": "8.0", //the deployment version in the webstore
       "module": "Sidebar",
        "userID": // hash value of uid here
    },

2) Some other interactions have to be logged explicitly, e.g, item opened, item closed (if accessible in gdocs), and cited as image, cited as url, as described in the section https://github.com/EEXCESS/eexcess/wiki/EEXCESS---Logging#explicit-logging

**Comment by chseifert** [comment]
This can be tested with the privacy-proxy https://eexcess-dev.joanneum.at/eexcess-privacy-proxy-issuer-1.0-SNAPSHOT/issuer/
