### ISSUE TITLE
Restyle search tool 

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/gdocs-plugin#29]
from gdocs review

"There’s a bit too much horizontal padding on the input field, please try to adjust this (seems like a byproduct of using type=”search” rather than “text”).
Also please add a bit of margin between the input field and the button, mainly to space out the ‘x’ delete and search action a bit.
Easy way to do this is to float the button to the right and reduce the width of the input field.  Nifty trick - if you give the parent div the attribute ‘overflow: auto”, it will give the field the correct height even though it’s contents are both floated."

**Comment by kunzstef** [comment]
Not clear what is meant with too much horizontal padding. The input’s padding is always 4px with input type text and search.
