### ISSUE TITLE
Settings - layout 

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/gdocs-plugin#31]
Comment from Google Review:
"In Settings - are you planning to add more Providers?  If not, please adjust the size of the div that contains the list of providers.  Feels unnecessary to have a scroll action to only display an extra half of an item."
My response so far: 
"The list of provider is dynamic and received on start-up and when the settings are adapted. Thus we don’t know beforehand how long the list will be and therefore considered a scroll action. "

Is this true that we receive the list of providers dynamically? I assume so, just checking :)

**Comment by kunzstef** [comment]
The list of providers is fetched dynamically from the server when the settings dialog is opened and we don't know beforehand how long the list will be. Because of this the scroll action is necessary.
