### ISSUE TITLE
Check manual search request format

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/gdocs-plugin#35]
If "Ada Lovelace" is put into the query field is this sent as "Ada Lovelace" or rather as Ada OR Lovelace (two context keywords). It should be the former

**Comment by kunzstef** [comment]
Currently every word of the query is submited as single context keyword with same weight. I talked last week with someone from the recommender project and he said it is ok so far. So it will be updated after the first deployment.

**Comment by chseifert** [comment]
Could be solved together when the request format needs to be updated (i.e. together with https://github.com/EEXCESS/gdocs-plugin/issues/33)

**Comment by chseifert** [comment]
For the GDocs Plugin I suggest for the deployment the following strategy:
- manual search: all selected words are sent as single words (weight is not there any more)
- text selection:  all selected words are sent as single words
  Rationale: Although this might lead to poor results from some partner recommenders, this is the behaviour end users are familiar with (from Google search for instance). 
  Making a more intelligent query would require noun-phrase detection and entity type assignment. I would defer this to a later stage.

**Comment by kunzstef** [comment]
All words are already sent as single words. Weight has been removed in this commit: b9e8952467dce09f67c1a67a2f6ad8a409726ba5

**Comment by chseifert** [comment]
I obviously confused myself with the above answer. 

What we need (and could implement quickly) is the following:
 When a user enters the 
  Query "Term1 Term2" Term3 (with quotation marks) 
**in the search box** then two context keywords should be sent, not three (thus, the phrases should be preserved).
This is basically a very simple query language, we introduce.
Is it possible to include this change in the current version? And sorry for the confusion :/
