### ISSUE TITLE
[Discussion] Place of link and URL insertion

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/gdocs-plugin#37]
I got the question why we insert the link below the current paragraph. I remember that you tried different methods (insert after selection, e.g,) and there was a (technical) reason why we decided to insert it after the paragraph. Could you please comment on that.

**Comment by chseifert** [comment]
user comment: 
"ich fände am sinnvollsten direkt nach der Selektion, jedenfalls wenn es wirklich um einen Link geht. Oder aber mit hochgestellter Ziffer und dann am Ende der Seite, als Fußnote.
Bei Bildern denke ich auch, nach dem Absatz macht Sinn. Kann man ja zur Not auch immer händisch verschieben."

@Fußnote: Vermutlich schwer zu realisieren, denn da muss man sich die Korrespondenz Link und Fußnote merken (und wenn man das eine löscht, auch das andere löschen).

**Comment by kunzstef** [comment]
The reason was that it was simpler using the same insert method for inserting images and links, because the method for inserting content directly after the selection was not finished and tested yet.
I finished it right now and will add it to the development version of this add-on.
