### ISSUE TITLE
Rename Menu Entry

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/gdocs-plugin#4]
- Rename the menu entry to E-Explorer and add a shortcut

**Comment by kunzstef** [comment]
Improve Sidebar title:
- The primary action here appears to be the search tool.  Consider changing the menu item label and the sidebar title to reflect this, rather than “Recommendations”.
  - If “Get Recommendations” is intended to be the primary action of this sidebar, you should consider ways to present it more prominently.

**Comment by kunzstef** [comment]
@mgrani where/to what should a shortcut be added?

**Comment by mgrani** [comment]
ALT+E or CMD+E i would say. anything that is memorable and does not conflict with other shortcuts

**Comment by chseifert** [comment]
meaning, a keyboard shortcut to start the same action as the button would do

**Comment by kunzstef** [comment]
You mean by pressing the shortcut recommendations should be searched for the current selected text? Then we have to discuss this. Currently the plugin automatically searches for recommendations if some text was selected. So this function is not necessary.

**Comment by chseifert** [comment]
Select and search automatically has one disadvantage - it will also be triggered when I simply want to copy and paste some text. Thus, I would go for a keyboard shortcut instead.

**Comment by kunzstef** [comment]
This is right. But registering event listeners outside of the sidebar's scope seems to be more complicated (https://code.google.com/p/google-apps-script-issues/issues/detail?id=306) -> work on this issue will be continued later

**Comment by chseifert** [comment]
Short cuts to menu entries currently prohibited by Google. Can't and won't fix ;-)
