### ISSUE TITLE
Change servers to stable servers

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/gdocs-plugin#42]
Server URLs should be changed to the stable versions (once they have been deployed).

**Comment by chseifert** [comment]
server components are deployed, https is enabled :)
Pls change the URLs to eexcess instead of eexcess-dev to connect to the stable servers.

**Comment by mgrani** [comment]
somehow we could not finished the deployment process for the E-Explorer Draft Version 8.

The tile-image size has been changed (which blocked it before), but now a new error appeared:

 "API Console project with the id specified in the manifest's api_console_project_id field, does not have Google Apps Marketplace SDK enabled."

Please take a look and redeploy the plugin.

**Comment by schloett** [comment]
just a follow-up: I guess for the tile-image, it was not only an issue of size, but also of image content. I would suggest to use something like this picture: https://lh6.googleusercontent.com/oJfwQ8_6-7D0BvYUk1sy4ym4vwjb37qlKOiaWwx8Hu1dXHSQi3oaGVhT63myF5EjAJ8F8M6fSw=s640-h400-e365-rw (and maybe also add the eexcess logo to it)

**Comment by schloett** [comment]
sry, forget about the postet image, does not comply with the policy "Platzieren Sie keine weißen Elemente entlang der Bildränder. Diese müssen klar definiert sein."
But the current one is a screenshot and hence will probably not pass the review as well "Verwenden Sie keinen Screenshot."

**Comment by mgrani** [comment]
lol, what else should we do? well, i will take your image, put eexcess there and draw a black border around it

**Comment by schloett** [comment]
sry, just checked it again, and white background might be fine. I guess it's the image for the addon webstore overview like here:
![addons](https://cloud.githubusercontent.com/assets/4618499/10907575/96e67b04-822b-11e5-9ec1-a117217b7be6.PNG)

**Comment by chseifert** [comment]
There is a draft version 9 now visible in the developer dashboard. What is the current status, what are problems? The current deployed version does not work anymore (due to the privacy proxy changing server urls), thus only the stable server urls are valid. Stefan,  could you give an update on this issue.

**Comment by kunzstef** [comment]
I tried to redeploy the same version, because I couldn't find any information yet about this problem. I will start right now working on it.

**Comment by kunzstef** [comment]
Should have been an issue in the Google App Script deployment process. I published the update now a third time with the same add-on version and had success. The update is now in the review phase.

**Comment by kunzstef** [comment]
The update has been approved for public use and is now available in the store.
