### ISSUE TITLE
Automatic Activation / Activation without reload

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/gdocs-plugin#44]
When the plugin is installed already, and a new document is created the add-on is visible but only with the 
EEXCESS-> Help menue (no start)

To get the add-on working, you need to "manage plugins" -> "activate for this document" and then RELOAD the document, to see the EEXCESS->Start button. 

Is there a automatic method, at least that the requirement of RELOADING the document is gone?

Maybe any magical setting/handler to achieve that.

**Comment by kunzstef** [comment]
The help menu entry is not set by the add-on. Only the start entry. This means the add-on was not loaded/activated yet. I couldn't found a workaround until now.

For next time I would suggest that we set an external help page for the add-on (e.g. the readme), that we can offer our user directly a workaround for problems like this.

**Comment by kunzstef** [comment]
an external help page was added with release v13
