### ISSUE TITLE
Insert image

### ISSUE THREAD

**Issue by jr-dig-orgel** [EEXCESS/gdocs-plugin#47]
Add the same icon, as added by the publications for inserting a link.

Feedback from Thinking Aloud Test

**Comment by kunzstef** [comment]
I cannot understand, which icon is meant. @jr-dig-orgel can you please explain this issue more detailed.

**Comment by jr-dig-orgel** [comment]
its marked red in the screenshot

![eexcess-google-docs](https://cloud.githubusercontent.com/assets/4506957/16578473/05e152e2-429b-11e6-9f75-a0622dfadf9a.png)

**Comment by kunzstef** [comment]
You mean I should replace the icons marked red with the the one marked green?
![untitled](https://cloud.githubusercontent.com/assets/5127621/16578782/aa55e1a2-429c-11e6-844b-be808af2dd91.png)

**Comment by jr-dig-orgel** [comment]
no, 
in the list of the images.
insert there the link-icon and show this always, not only on mouse hover.

![eexcess-google-docs-ii](https://cloud.githubusercontent.com/assets/4506957/16579111/744a21a2-429e-11e6-92ed-d7278fd04fa3.png)
