### ISSUE TITLE
Remove get Recommendations Button

### ISSUE THREAD

**Issue by mgrani** [EEXCESS/gdocs-plugin#6]
Instead when a text is selected, paste it to the search box and search automatically.

**Comment by kunzstef** [comment]
Also check for timeout:
- The “Get Recommendations” tool needs some work.  It took me a while to understand what it was and how it works - I had to visit your website and read about it before I fully understood.  Aspects to improve:
  - Description is needed.  How is it different from the normal searching?  What exactly are recommendations, in this context?  
  - Instructions are needed.  I assumed that the recommendations where based on the search input field.  It needs to be more explicit to the user that they need to select text from the document to use this.
  - Consider subtle ways to accomplish this - adding a paragraph of text isn’t a great solution either.  
  - Also - it displays the error: The server timed out waiting for the request  almost every time I use this tool.  Please investigate.

**Comment by chseifert** [comment]
Regarding the time-outs and result quality - this will be improved on the server side. Currently the gdocs plugin is using the old (stable) version of the server. I would stick to that for the alpha version and then migrate to the development version (which has a different api) for the next milestone.
