### ISSUE TITLE
Link brand to project website

### ISSUE THREAD

**Issue by kunzstef** [EEXCESS/gdocs-plugin#8]
Add link to project website if logo was  clicked. Think of branding change.
- Logo - consider making it a link to your website.
  - Also - I’m somewhat confused by your branding:  EXCESS, Recommendations by EXCESS.  Does it need to state your name twice?  Seems redundant to me…

**Comment by kunzstef** [comment]
TODO: discuss branding change

**Comment by chseifert** [comment]
I would do this in the bottom with the logo. 
EEXCESS logo smaller, then instead of "Recommendations by EEXCESS" "Search digital library content" und "more info" daneben. More Info is a link to http://eexcess.eu.
